version: "3"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 10.15.0.0/16

services:
  haproxy:
    container_name: haproxy
    image: icodex/docker-haproxy
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - default
    environment:
      - BACKEND=nginx:80
    volumes:
      - ./etc/haproxy/certs:/usr/local/etc/haproxy/certs/:ro
    restart: always

  nginx:
    image: nginx:alpine
    expose:
      - 80
    env_file:
      - ".env"
    volumes:
      - ./etc/nginx/restrictions.conf:/etc/nginx/restrictions.conf:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template:ro
      - ./web:/var/www/html:rw
    networks:
      - default
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php-fpm
      - mysqld

  php-fpm:
    image: icodex/php-fpm:${PHP_VERSION}
    env_file:
      - ".env"
    expose:
      - 3000
    networks:
      - default
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./etc/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./data/log:/var/log:rw
      - ./data/temp:/temp:rw
      - ./web:/var/www/html:rw
    restart: always

  redis:
    image: redis:latest
    expose:
      - 6379
    networks:
      - default
    volumes:
      - ./etc/redis/redis.conf:/etc/redis/redis.conf:rw
      - ./data/redis:/data:rw
    command: redis-server /etc/redis/redis.conf
    privileged: true
    restart: always

  composer:
    image: "composer"
    volumes:
      - ./web/app:/app:rw
    command: install

  phpmyadmin:
    image: phpmyadmin
    networks:
      - default
    expose:
      - 80
    env_file:
      - ".env"
    restart: always
    depends_on:
      - mysqld

  mysqld:
    image: mariadb:${MYSQL_VERSION}
    networks:
      - default
    expose:
      - 3306
    env_file:
      - ".env"
    volumes:
      - ./data/db/mysql:/var/lib/mysql:rw
    restart: always
