version: '3'

networks:
  vpcbr:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 10.15.0.0/16

services:
    web:
        image: nginx:alpine
        links:
            - php-fpm:php-fpm
            - mysqldb:mysqldb
            - phpmyadmin:phpmyadmin
        env_file:
            - ".env"
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        # ports:
        #     - "80:80"
        #     - "443:443"
        networks:
            vpcbr:
                ipv4_address: 10.15.0.2
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php-fpm
            - mysqldb
        
    php-fpm:
        image: icodex/php-fpm:${PHP_VERSION}
        restart: always
        env_file:
            - ".env"
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./web:/var/www/html"

    composer:
        image: "composer"
        volumes:
            - "./web/app:/app"
        command: install

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        # ports:
        #     - "8080:80"
        networks:
            vpcbr:
                ipv4_address: 10.15.0.5
        env_file:
            - ".env"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb

    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        # ports:
        #     - "3306:3306"
        networks:
            vpcbr:
                ipv4_address: 10.15.0.3
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
