version: '3'

networks:
  vpcbr:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 10.15.0.0/16

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        links:
            - php-fpm:php-fpm
            - mysqld:mysqld
            - phpmyadmin:phpmyadmin
        env_file:
            - ".env"
        volumes:
            - "./etc/nginx/restrictions.conf:/etc/nginx/restrictions.conf"
            - "./etc/nginx/phpmyadmin.conf:/etc/nginx/phpmyadmin.conf"
            - "./etc/nginx/proxy.inc:/etc/nginx/proxy.inc"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        # ports:
        #     - "80:80"
        #     - "443:443"
        networks:
            vpcbr:
                ipv4_address: 10.15.0.2
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php-fpm
            - mysqld
        
    php-fpm:
        image: icodex/php-fpm:${PHP_VERSION}
        container_name: php-fpm
        restart: always
        env_file:
            - ".env"
        networks:
            vpcbr:
                ipv4_address: 10.15.0.4
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./web:/var/www/html"

    composer:
        image: "composer"
        volumes:
            - "./web/app:/app"
        command: install

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        # ports:
        #     - "8080:80"
        networks:
            vpcbr:
                ipv4_address: 10.15.0.5
        env_file:
            - ".env"
        restart: always
        depends_on:
            - mysqld

    mysqld:
        image: mysql:${MYSQL_VERSION}
        container_name: mysqld
        restart: always
        # ports:
        #     - "3306:3306"
        networks:
            vpcbr:
                ipv4_address: 10.15.0.3
        env_file:
            - ".env"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
